### ISSUE TITLE
Request failed with status code 401 Okta OAuth with CloudFront Distro

### ISSUE THREAD

**Issue by jmmizerany** [aws-samples/lambdaedge-openidconnect-samples#33]
I have set up Okta OAuth to be in front of a CloudFront distro that uses an S3 bucket as the origin. I am able to authenticate with Okta, but after being redirected back to the CloudFront distro I get the following error from the Lambda@Edge function:

`
"error": {
        "message": "Request failed with status code 401",
        "stack": "Error: Request failed with status code 401\n    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
    },
    "logName": "auth",
    "date": " "
}
`
Looking at the log folder in the S3 I can see I get a 500 error from the call back url for my CloudFront distro, but I have followed the steps and seem to always get the same result. Not sure what other steps I can take but any help would be appreciated

**Comment by jmmizerany** [comment]
Issue has been resolved
