### ISSUE TITLE
Request failed with Internal server error 500 on accessing the Cloudfront url from browser, but the lambda logs have error 400

### ISSUE THREAD

**Issue by sfc-gh-spanda** [aws-samples/lambdaedge-openidconnect-samples#45]
Hi Team, 
I have set up Cognito OAuth to be in front of a CloudFront distro that uses an S3 bucket as the origin.Accessing the CloudFront distro I get the following error from the Lambda@Edge function:

    "error": {
        "message": "Request failed with status code 400",
        "stack": "Error: Request failed with status code 400\n    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
    },
    "logName": "auth",
    "date": "2022-12-15T10:06:07.472Z"
}

**Comment by noyceguy** [comment]
@sfc-gh-spanda thank you for opening this issue. Are you able to successfully integrate with Cognito? We'll work on updating the error code.
