### ISSUE TITLE
The code size is larger than 1mb, which is larger than the allowed size for viewer event in cloudFront

### ISSUE THREAD

**Issue by dyennamdh** [aws-samples/lambdaedge-openidconnect-samples#50]
Hi,
The code size is larger than 1mb. which is larger than he allowed size for viewer event in cloudFront.
I followed some of the steps outlined in [issue 47](https://github.com/aws-samples/lambdaedge-openidconnect-samples/issues/47) which reduced the size a little bit but not enough.

I deleted the dist folder under `node_modules/base64url/dist` to get under the 1mb limit. But not sure if thats the correct way of going about it.

Any suggestion to get over this issue?

Regards,
Dheeraj

**Comment by noyceguy** [comment]
Hi @dyennamdh thank you for reaching out. Is there a specific reason or use-case for manually deploying the zip instead of using SAM to deploy? How large is the given zip file after you manually upload it?

**Comment by jonsage** [comment]
Hi @dyennamdh, to make it small enough to manually zip and deploy I used [node-prune](https://github.com/tj/node-prune) and also removed `lib/log/index.d.ts` as we don't need type definitions when deployed.

Finally I ran `zip -r lambda.zip lib node_modules auth.js sm-key.txt`

**Comment by dyennamdh** [comment]
> Hi @dyennamdh thank you for reaching out. Is there a specific reason or use-case for manually deploying the zip instead of using SAM to deploy? How large is the given zip file after you manually upload it?

Hello @noyce-cloud Main reason is we are trying to standardize our deploys, not trying to introduce any new tools just for a single use case.
In this case, once we zip it, then we would never have to touch it again just to add oAuth functionality to it.

**Comment by dyennamdh** [comment]
> Hi @dyennamdh thank you for reaching out. Is there a specific reason or use-case for manually deploying the zip instead of using SAM to deploy? How large is the given zip file after you manually upload it?

Hello @noyce-cloud Main reason is we are trying to standardize our deploys, not trying to introduce any new tools just for a single use case.
In this case, once we zip it, then we would never have to touch it again just to add oAuth functionality to it.

**Comment by jbrough** [comment]
esbuild gets it down to 150K:

```
esbuild auth.js --bundle --outfile=main.js --platform=node  --external:'aws-sdk' && zip -r build/function.zip main.js
```

```
❯ ls -lha build/function.zip
-rw-r--r--  1 jamieb  wheel   153K  9 May 16:45 build/function.zip
```

**Comment by efarjun** [comment]
I am getting the following error when attempting to use a zipped file, either with the mentioned esbuild command or zipping it and uploading it myself:

{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'auth'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'auth'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/Runtime.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:225:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1114:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)",
        "    at Module.load (internal/modules/cjs/loader.js:979:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:819:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

This is probably an easy fix if anybody would be kind enough to help!
